theme = "catppuccin_mocha"

[editor]
mouse = false
middle-click-paste = false
shell = ["nu", "-c"] 
line-number = "relative"
cursorline = true
rulers = [80]
bufferline = "multiple"

[editor.statusline]
left = ["mode", "file-name", "read-only-indicator", "file-modification-indicator", "position"]
right = ["spinner", "diagnostics", "selections", "register", "file-encoding", "version-control", "file-type"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode
